# Generated by Django 4.1.7 on 2023-03-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('node_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('in_channel', models.CharField(max_length=100)),
                ('out_channel', models.CharField(max_length=100)),
                ('kernel_size', models.IntegerField()),
                ('stride', models.IntegerField()),
                ('padding', models.IntegerField()),
            ],
        ),
    ]
